// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIRioE0ukhaaZkAZiet_Xp4bcydK9x7VM',
    appId: '1:126453952717:web:72ca3c568e5aa84cb43984',
    messagingSenderId: '126453952717',
    projectId: 'ai-todolist-36a96',
    authDomain: 'ai-todolist-36a96.firebaseapp.com',
    storageBucket: 'ai-todolist-36a96.firebasestorage.app',
    measurementId: 'G-V5MXHWZB83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUF3bI7TJYJP-H2n98HOBy0pwr9BH8_OI',
    appId: '1:126453952717:android:8798ff86b71730b5b43984',
    messagingSenderId: '126453952717',
    projectId: 'ai-todolist-36a96',
    storageBucket: 'ai-todolist-36a96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ86PQ33AQp1cZzEqcOQwfU5ZBQ1EPJLM',
    appId: '1:126453952717:ios:2a3d8c081f66533fb43984',
    messagingSenderId: '126453952717',
    projectId: 'ai-todolist-36a96',
    storageBucket: 'ai-todolist-36a96.firebasestorage.app',
    iosClientId: '126453952717-dbdfdlgcfueoj7piasjna7nkdgk6obmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiassistant1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ86PQ33AQp1cZzEqcOQwfU5ZBQ1EPJLM',
    appId: '1:126453952717:ios:2a3d8c081f66533fb43984',
    messagingSenderId: '126453952717',
    projectId: 'ai-todolist-36a96',
    storageBucket: 'ai-todolist-36a96.firebasestorage.app',
    iosClientId: '126453952717-dbdfdlgcfueoj7piasjna7nkdgk6obmk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiassistant1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIRioE0ukhaaZkAZiet_Xp4bcydK9x7VM',
    appId: '1:126453952717:web:ab2dd99f2df4114ab43984',
    messagingSenderId: '126453952717',
    projectId: 'ai-todolist-36a96',
    authDomain: 'ai-todolist-36a96.firebaseapp.com',
    storageBucket: 'ai-todolist-36a96.firebasestorage.app',
    measurementId: 'G-03313FVY1X',
  );

}